cat99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :cats do
    resources :cat_rental_requests, only: [:index]
  end
  
  resources :cat_rental_requests, only: [:create, :show, :edit, :new, :update, :destroy]
end

cat99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  CATCOLORS = %w( orange black white tuxedo tabby calico purple )
  validates :birth_date, :name, :description, presence: true
  validates :sex, inclusion: { in: %w(M F) }
  validates :color, inclusion: { in: CATCOLORS }
  
  def age 
    Time.now.year - self.birth_date.year
  end
  
  has_many :cat_rental_requests,
    foreign_key: :cat_id,
    class_name: 'CatRentalRequest',
    dependent: :destroy
  
end

cat99/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w(APPROVED DENIED PENDING) }, presence: true
  
  validate :overlapping_approved_requests
  
  belongs_to :cat
  
  private
  
  def overlapping_requests
    rentals = self.cat.cat_rental_requests.reject { |rental| rental.id == self.id }
    rentals.select { |rental| !(rental.start_date > self.end_date || rental.end_date < self.start_date) }
  end
  
  def overlapping_approved_requests
    overlapping_requests.any? { |request| request.status == 'APPROVED' }
  end
end

cat99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

cat99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @cat = Cat.find(params[:cat_id])
    @cat_rentals = @cat.cat_rental_requests.order(end_date: :desc)
  end
  
  def show
    redirect_to cat_cat_rental_requests_url
  end
  
  def create
    cat_rental = CatRentalRequest.new(cat_rental_params)
    
    if cat_rental.save 
      redirect_to cat_cat_rental_requests_url
    else 
      render plain: cat_rental.errors.full_messages
    end
  end
  
  def new
    @cats = Cat.all
    @cat_rental = CatRentalRequest.new
  end
  
  def update
    cat_rental = CatRentalRequest.find(params[:id])
    
    if cat_rental.update_attributes(cat_rental_params)
      redirect_to cat_cat_rental_requests_url
    else 
      redirect_to edit_cat_rental_request
    end 
  end
  
  def edit
    @cats = Cat.all
    @cat_rental = CatRentalRequest.find(params[:id])
  end
  
  def destroy
    CatRentalRequest.find(params[:id]).destroy
    redirect_to cat_cat_rental_requests_url
  end
  
  private
  
  def cat_rental_params
    params.require(:cat_rental).permit(:cat_id, :start_date, :end_date, :status)
  end

end

cat99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  def index
    @cats = Cat.all
  end
  
  def show
    @cat = Cat.find(params[:id])
  end
  
  def new
    @cat = Cat.new
  end
  
  def create
    cat = Cat.new(cat_params)
    if cat.save
      redirect_to cat_url(cat)
    else
      render plain: cat.errors.full_messages
    end
  end
  
  def edit
    @cat = Cat.find(params[:id])
  end
  
  def update
    cat = Cat.find(params[:id])
    
    if cat.update_attributes(cat_params)
      redirect_to cat_url(cat)
    else
      redirect_to edit_cat(cat)
    end
    
  end
  
  def destroy
    Cat.find(params[:id]).destroy
  end
  
  private
  
  #Strong Params
  def cat_params #strictly for user input
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
  
end

cat99/app/views/cat_rental_requests/_form.html.erb
<form class="" action= '<%= action %>' method="POST">
  <% if type == 'edit' %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>
  
  
  <label for=""></label>
  <select class="" name="">
    <option <%= 'selected' if type != 'edit' %> disabled>-- Please Select Cat --</option>
    <% cats.each do |cat| %>
    <option <%= 'selected' if cat.id == cat_rental.cat_id %>  value= "<%= cat.id %>"><%= cat.id %> : <%= cat.name %></option>
    <% end %>
  </select>
  
  
  
</form>

cat99/app/views/cat_rental_requests/edit.html.erb
<%= render 'form', cats: @cats, type: 'edit', cat_rental: @cat_rental, action: cat_rental_request_url, button: 'Update Rental' %>

cat99/app/views/cat_rental_requests/index.html.erb
<table>
  <%= @cat.name %>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
  </tr>
  <% @cat_rentals.each do |rental| %>
  <tr>
    <td><%= rental.start_date %></td>
    <td><%= rental.end_date %></td>
  </tr>
  <% end %>
</table>

cat99/app/views/cat_rental_requests/new.html.erb
<%= render 'form', cats: @cats, cat_rental: @cat, action: cat_rental_requests_url, button: 'Request Cat Rental'%>