W4D4_music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]
  
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

end

W4D4_music_app/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  title      :string           not null
#  ord        :integer          not null
#  regular    :boolean          default(TRUE), not null
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :album_id, :title, :ord, presence: true
  validates :regular, inclusion: [true, false]
  validates :ord, uniqueness: true

  belongs_to :album,
    foreign_key: :album_id,
    class_name: 'Album'
end

W4D4_music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!

  def new
    @albums = Album.all
    @album = Album.find_by(id: params[:album_id])
  end

  def create
    track = Track.new(track_params)
    album = Album.find_by(id: track_params[:album_id].to_i)

    if track.save
      redirect_to track_url(track)
    else
      flash[:errors] = track.errors.full_messages
      redirect_to new_album_track_url(album)
    end
  end

  def show
    @track = Track.find_by(id: params[:id])
    @album = Album.find_by(id: @track.album_id)
  end

  def edit
    @albums = Album.all
    @track = Track.find_by(id: params[:id])
    @album = Album.find_by(id: @track.album_id)
  end

  def update
    track = Track.find_by(id: params[:id].to_i)
    album = Album.find_by(id: track.album_id)
    if track.update_attributes(track_params)
      redirect_to track_url(track)
    else
      redirect_to edit_track_url(track)
    end
  end

  def destroy
    track = Track.find_by(id: params[:id])
    album = Album.find_by(id: track.album_id)
    if track.destroy
      redirect_to album_url(album)
    else
      flash[:errors] = 'Track cannot be found'
      redirect_to album_url(album)
    end
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :title, :ord, :lyrics)
  end
end

W4D4_music_app/app/views/tracks/edit.html.erb
<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label>Title
    <input type="text" name="track[title]" value="<%= @track.title %>">
  </label>

  <label>Ord
    <input type="number" min='1' name="track[ord]" value="<%= @track.ord %>">
  </label>

  <label>Albums
    <select name="track[album_id]">
      <option disabled selected>--Please Select a Band--</option>
      <% @albums.each do |album| %>
      <option <%= 'selected' if album.id == @album.id %> value="<%= album.id %>"><%= album.title %></option>
      <% end %>
    </select>
  </label>

  <div>
    <label>Regular
      <input <%= 'checked' if @track.regular %> type="radio" name="track[studio]" value="true">
    </label>
    <label>Bonus
      <input <%= 'checked' if !@track.regular %> type="radio" name="track[studio]" value="false">
    </label>
  </div>

  <label>Lyrics
    <textarea name="track[lyrics]" rows="8" cols="80"><%= @track.lyrics %></textarea>
  </label>

  <input type="submit" value="Update Track">
</form>

W4D4_music_app/app/views/tracks/new.html.erb
<form action="<%= tracks_url %>" method="post">
  <%= auth_token %>

  <label>Title
    <input type="text" name="track[title]" value="">
  </label>

  <label>Ord
    <input type="number" min='1' name="track[ord]" value="">
  </label>

  <label>Albums
    <select name="track[album_id]">
      <option disabled selected>--Please Select a Band--</option>
      <% @albums.each do |album| %>
      <option <%= 'selected' if album.id == @album.id %> value="<%= album.id %>"><%= album.title %></option>
      <% end %>
    </select>
  </label>

  <div>
    <label>Regular
      <input type="radio" name="track[studio]" value="true">
    </label>
    <label>Bonus
      <input type="radio" name="track[studio]" value="false">
    </label>
  </div>

  <label>Lyrics
    <textarea name="track[lyrics]" rows="8" cols="80"></textarea>
  </label>

  <input type="submit" value="Create Track">
</form>

W4D4_music_app/app/views/tracks/show.html.erb
<h1><%=@track.title%></h1>

<div>
  <%= @track.lyrics %>
</div>

<a href="<%= album_url(@album) %>">back to album: <%= @album.title %></a>