W5D2/reddit/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:create, :new, :destroy]
  resources :subs
  
  resources :posts, except: [:index] do
    resources :comments, only: [:new, :create]
  end
  
  resources :comments, only: [:create, :destroy, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W5D2/reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :subs, :author, presence: true
  
  has_many :post_subs

  has_many :subs,
    through: :post_subs,
    source: :sub

  belongs_to :author,
  class_name: :User,
  foreign_key: :author_id
  
  has_many :comments
end

W5D2/reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_author, only: [:update, :destroy]
  def new
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    debugger
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to subs_url
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [] )
  end
  
  def ensure_author
    @post = Post.find(params[:id])
    unless current_user == @post.author
      redirect_to post_url(@post) 
      flash.now[:errors] = ['You do not author this post']
    end
  end
end

W5D2/reddit/app/helpers/posts_helper.rb
module PostsHelper
  def commments_to_parse(comment, depth = 0)
    return [comment.content, depth] if comment.comments.empty?
    family = []
    comment.comments.each do 
      family += commments_to_parse(comment, depth + 1)
    end
    return family
  end
end

W5D2/reddit/app/views/posts/_comment.html.erb
<li>
<form class="" action="<%= comment_url(comment) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="" value="Remove Comment">
</form>
<%= link_to comment.content, comment_url(comment) %>
  <ul>
    <% comment.comments.each do |comment| %>
      <%= render 'comment', comment: comment %>
    <% end %>
  </ul>
</li>

W5D2/reddit/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

W5D2/reddit/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

W5D2/reddit/app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>


Edit Post 

<form action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="patch">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <label>
    <textarea name="post[content]" rows="8" cols="80"><%= @post.content %></textarea>
  </label>
  <br>
  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
  <label>
    <input <%= 'checked' if @post.subs.include?(sub) %> type="checkBox" name="post[sub_ids][]" value="<%= sub.id %>">
    <%= sub.title %>
  </label>
  <br>
  <% end %>
  
  <input type="submit" name="" value="Update Post">
</form>

W5D2/reddit/app/views/posts/new.html.erb
New Post

<form action="<%= posts_url %>" method="post">
  <%= auth_token %>
  <label>Title
    <input type="text" name="post[title]" value="">
  </label>
  <label>URL
    <input type="text" name="post[url]" value="">
  </label>
  <label>
    <textarea name="post[content]" rows="8" cols="80"></textarea>
  </label>
  <br>
  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
  <label>
    <input type="checkBox" name="post[sub_ids][]" value="<%= sub.id %>">
    <%= sub.title %>
  </label>
  <br>
  <% end %>
  
  <input type="submit" name="" value="Create Post">
</form>

W5D2/reddit/app/views/posts/show.html.erb
Title:
<%= @post.title %>
URL:
<%= @post.url %>
Content:
<%= @post.content %>
Author:
<%= @post.author.username %>

<form action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="" value="Delete Post">
</form>

<br>

Subs:
<ul>
  <% @post.subs.each do |sub| %>
  <li>
    <%= sub.title %>
  </li>
  <% end %>
</ul>

<a href="<%= subs_url %>">Subs</a>
<a href="<%= edit_post_url(@post) %>">Edit Post</a>

<h3>Comments:</h3>
<form class="" action="<%= post_comments_url(@post) %>" method="post">
  <%= auth_token %>
  <textarea name="comment[content]" rows="2" cols="80" placeholder="This is my fight song. My take back my life song. Prove I'm all right song."></textarea>
  <input type="submit" name="" value="Add Comment">
</form>

<ul>
  <% @post.comments.each do |comment| %>
    <%= render 'comment', comment: comment %>
  <% end %>
</ul>

W5D2/reddit/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>